apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "juris-ai-helper.name" . }}-config
data:
  JURIS_DEBUG: {{ .Values.backend.debug | quote }}

  # Configuration Ollama
  JURIS_OLLAMA_BASE_URL: {{ .Values.backend.ollamaBaseUrl | quote }}
  JURIS_OLLAMA_TIMEOUT: {{ .Values.backend.ollamaTimeout | quote }}

  # Limites de fichiers (en Mo)
  JURIS_MAX_PDF_SIZE_MB: {{ .Values.backend.maxPdfSizeMb | quote }}
  JURIS_MAX_CSV_SIZE_MB: {{ .Values.backend.maxCsvSizeMb | quote }}

  # Mod√®les
  JURIS_OLLAMA_MODEL: {{ .Values.backend.ollamaModel | quote }}
  JURIS_OLLAMA_AVAILABLE_MODELS: {{ .Values.backend.ollamaAvailableModels | quote }}
  API_URL: {{ .Values.frontend.apiUrl | quote }}